markdown: rdiscount
permalink: /:year/:month/:day/:title/
url: http://scola.github.io
name:scola
author: scola
duoshuo:scola
qq: 454651583
email: scola@gmail.com
weibo: 1958231132
github: scola
pygments: true
safe: true
paginate: 15
about: ""
show_drafts: false
