markdown: rdiscount
permalink: /:title/
url: http://scola.github.io
name: scola的个人笔记
author: scola
duoshuo: scola
qq: 325862401
email: shaozheng.wu@gmail.com
twitter: wushaozheng
weibo: 1894900993
github: scola
pygments: true
safe: true
paginate: 20
about: scola的个人笔记fork from [Yonsm的个人博客](https://github.com/Yonsm/NET)，主要用于记录折腾笔记，以便下次重复操作,也记录一些生活感想和琐事
show_drafts: false
