markdown: rdiscount
permalink: /:year/:month/:day/:title/
url: http://peizerao.github.io
name: godlike的世界
author: peizerao
duoshuo: godlike的世界
qq: 454651583
email: peizerao@gmail.com
weibo: 1958231132
github: peizerao
pygments: true
safe: true
paginate: 15
about: ""
show_drafts: false
