markdown: rdiscount
permalink: /:year/:month/:day/:title/
url: http://scola.github.io
name: scola的个人笔记
author: scola
duoshuo: scola的个人笔记
qq: 325862401
email: shaozheng.wu@gmail.com
weibo: 1894900993
github: scola
pygments: true
safe: true
paginate: 15
about: scola的个人笔记fork from Yonsm的个人博客，主要用于记录折腾笔记，以便下次重复操作
show_drafts: false
