markdown: rdiscount
permalink: /:year/:month/:day/:title/
url: http://peizerao.github.io
name: godlike的世界
author: peizerao
duoshuo: espuppet
github: peizerao
pygments: true
safe: true
paginate: 15
about: ""
show_drafts: false
